/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaproject.view;

import java.awt.event.ActionListener;
import javax.swing.JPasswordField;

/**
 *
 * @author ACER
 */
public class NewJPanel extends javax.swing.JPanel {

    /**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        PhoneNumber = new javax.swing.JLabel();
        PhoneNumberField = new javax.swing.JTextField();
        ShowButton1 = new javax.swing.JButton();
        ShowButton2 = new javax.swing.JButton();
        ShowButton4 = new javax.swing.JButton();
        Password2 = new javax.swing.JLabel();
        Password3 = new javax.swing.JLabel();
        PictureButton = new javax.swing.JButton();
        Registration = new javax.swing.JLabel();
        FirstName = new javax.swing.JLabel();
        FirstNameFiled = new javax.swing.JTextField();
        LastName = new javax.swing.JLabel();
        LastNameFiled = new javax.swing.JTextField();
        Address = new javax.swing.JLabel();
        AddressFiled = new javax.swing.JTextField();
        Email = new javax.swing.JLabel();
        EmailFiled = new javax.swing.JTextField();
        Password = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        ShowButton3 = new javax.swing.JButton();
        RePassword = new javax.swing.JLabel();
        RePasswordField = new javax.swing.JPasswordField();
        ShowButton5 = new javax.swing.JButton();
        Security = new javax.swing.JLabel();
        PictureButton1 = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        BackToLogin = new javax.swing.JButton();
        SecurityAnswer = new javax.swing.JTextField();

        jMenuItem1.setText("jMenuItem1");

        jMenuItem2.setText("jMenuItem2");

        PhoneNumber.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        PhoneNumber.setForeground(new java.awt.Color(255, 255, 255));
        PhoneNumber.setText("Phone Number:");

        ShowButton1.setText("Show");

        ShowButton2.setText("Show");

        ShowButton4.setText("Show");

        Password2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password2.setForeground(new java.awt.Color(255, 255, 255));
        Password2.setText("Security Key:");

        Password3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password3.setForeground(new java.awt.Color(255, 255, 255));
        Password3.setText("Security Key:");

        PictureButton.setBackground(new java.awt.Color(51, 51, 255));
        PictureButton.setForeground(new java.awt.Color(255, 255, 255));
        PictureButton.setText("Upload Picutre");

        setBackground(new java.awt.Color(0, 102, 102));

        Registration.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Registration.setForeground(new java.awt.Color(255, 255, 255));
        Registration.setText("Registration Page");

        FirstName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        FirstName.setForeground(new java.awt.Color(255, 255, 255));
        FirstName.setText("First Name:");

        LastName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        LastName.setForeground(new java.awt.Color(255, 255, 255));
        LastName.setText("Last Name:");

        Address.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Address.setForeground(new java.awt.Color(255, 255, 255));
        Address.setText("Address:");

        Email.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Email.setForeground(new java.awt.Color(255, 255, 255));
        Email.setText("Email:");

        Password.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Password.setForeground(new java.awt.Color(255, 255, 255));
        Password.setText("Password:");

        ShowButton3.setText("Show");

        RePassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        RePassword.setForeground(new java.awt.Color(255, 255, 255));
        RePassword.setText("Re-entred Password");

        ShowButton5.setText("Show");

        Security.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Security.setForeground(new java.awt.Color(255, 255, 255));
        Security.setText("Security:");

        PictureButton1.setBackground(new java.awt.Color(51, 51, 255));
        PictureButton1.setForeground(new java.awt.Color(255, 255, 255));
        PictureButton1.setText("Upload Picutre");

        RegisterButton.setBackground(new java.awt.Color(255, 0, 0));
        RegisterButton.setForeground(new java.awt.Color(255, 255, 255));
        RegisterButton.setText("Register");
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });

        BackToLogin.setBackground(new java.awt.Color(153, 153, 153));
        BackToLogin.setForeground(new java.awt.Color(255, 255, 255));
        BackToLogin.setText("Back to Login");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Email, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(FirstName)
                                .addComponent(LastName, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(Address, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Password, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(RePassword)
                            .addComponent(Security))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(RePasswordField)
                            .addComponent(PasswordField)
                            .addComponent(EmailFiled)
                            .addComponent(AddressFiled)
                            .addComponent(LastNameFiled)
                            .addComponent(FirstNameFiled)
                            .addComponent(PictureButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 221, Short.MAX_VALUE)
                            .addComponent(RegisterButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(BackToLogin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(SecurityAnswer))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ShowButton5)
                    .addComponent(ShowButton3))
                .addGap(96, 96, 96))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Registration, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(156, 156, 156))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(Registration)
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(FirstName)
                    .addComponent(FirstNameFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LastName)
                    .addComponent(LastNameFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Address)
                    .addComponent(AddressFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(EmailFiled, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Email))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password)
                    .addComponent(ShowButton3)
                    .addComponent(PasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ShowButton5)
                    .addComponent(RePassword)
                    .addComponent(RePasswordField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Security)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(SecurityAnswer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PictureButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(RegisterButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(BackToLogin)
                .addContainerGap(17, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        // TODO add your handling code here:
         new NewJPanel().setVisible(true);
            dispose();
    }//GEN-LAST:event_RegisterButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Address;
    private javax.swing.JTextField AddressFiled;
    private javax.swing.JButton BackToLogin;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailFiled;
    private javax.swing.JLabel FirstName;
    private javax.swing.JTextField FirstNameFiled;
    private javax.swing.JLabel LastName;
    private javax.swing.JTextField LastNameFiled;
    private javax.swing.JLabel Password;
    private javax.swing.JLabel Password2;
    private javax.swing.JLabel Password3;
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JLabel PhoneNumber;
    private javax.swing.JTextField PhoneNumberField;
    private javax.swing.JButton PictureButton;
    private javax.swing.JButton PictureButton1;
    private javax.swing.JLabel RePassword;
    private javax.swing.JPasswordField RePasswordField;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel Registration;
    private javax.swing.JLabel Security;
    private javax.swing.JTextField SecurityAnswer;
    private javax.swing.JButton ShowButton1;
    private javax.swing.JButton ShowButton2;
    private javax.swing.JButton ShowButton3;
    private javax.swing.JButton ShowButton4;
    private javax.swing.JButton ShowButton5;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JTextField getFirstNameTextField(){
        return FirstNameFiled;
    }
    public javax.swing.JTextField getLastNameTextField(){
        return LastNameFiled;
    }
    public javax.swing.JTextField getAddressTextField(){
        return AddressFiled;
    }
    public javax.swing.JTextField getEmailTextField(){
        return EmailFiled;
    }
     public javax.swing.JPasswordField getPasswordTextField(){
        return (JPasswordField) PasswordField;
    }
     public javax.swing.JPasswordField getRePasswordTextField(){
        return (JPasswordField) RePasswordField;
    }
    public javax.swing.JTextField getSecurityAnswerTextField(){
        return SecurityAnswer;
    }
     public void RegistrationUser(ActionListener listener){
         RegisterButton.addActionListener(listener);
     }
    public void dispose() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
   
