/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package vroomproject.view;

/**
 *
 * @author Dell
 */
public class Forget extends javax.swing.JPanel {

    /**
     * Creates new form Forget
     */
    public Forget() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Resettext = new javax.swing.JLabel();
        newpassword = new javax.swing.JLabel();
        confirmpassword = new javax.swing.JLabel();
        confim = new javax.swing.JPasswordField();
        passwordreminder = new javax.swing.JLabel();
        Confimtext = new javax.swing.JLabel();
        newpass = new javax.swing.JPasswordField();
        confirmshowbutton = new javax.swing.JButton();
        showbutton1 = new javax.swing.JButton();
        texttopic = new javax.swing.JLabel();
        resetbutton = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        Resettext.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Resettext.setForeground(new java.awt.Color(255, 255, 255));
        Resettext.setText("Create new password");

        newpassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        newpassword.setForeground(new java.awt.Color(255, 255, 255));
        newpassword.setText("New password");

        confirmpassword.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        confirmpassword.setForeground(new java.awt.Color(255, 255, 255));
        confirmpassword.setText("Confim Password");

        confim.setText("jPasswordField1");

        passwordreminder.setForeground(new java.awt.Color(255, 255, 255));
        passwordreminder.setText("Password must be atleast 8 character. ");

        Confimtext.setForeground(new java.awt.Color(255, 255, 255));
        Confimtext.setText("Both password must be same.");

        newpass.setText("jPasswordField2");

        confirmshowbutton.setText("Show");

        showbutton1.setText("Show");

        texttopic.setForeground(new java.awt.Color(255, 255, 255));
        texttopic.setText("Your password must be different from previous");

        resetbutton.setBackground(new java.awt.Color(0, 153, 153));
        resetbutton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        resetbutton.setForeground(new java.awt.Color(255, 255, 255));
        resetbutton.setText("Reset Password");

        jButton1.setBackground(new java.awt.Color(0, 153, 153));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back to login");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(Resettext))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(43, 43, 43)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Confimtext)
                            .addComponent(passwordreminder)
                            .addComponent(newpassword)
                            .addComponent(confirmpassword)
                            .addComponent(newpass, javax.swing.GroupLayout.DEFAULT_SIZE, 246, Short.MAX_VALUE)
                            .addComponent(confim))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(confirmshowbutton)
                            .addComponent(showbutton1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 101, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(texttopic)
                        .addGap(93, 93, 93))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(resetbutton, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(135, 135, 135))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Resettext)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(texttopic)
                .addGap(38, 38, 38)
                .addComponent(newpassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(showbutton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passwordreminder)
                .addGap(18, 18, 18)
                .addComponent(confirmpassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(confim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(confirmshowbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Confimtext)
                .addGap(18, 18, 18)
                .addComponent(resetbutton)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(203, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Confimtext;
    private javax.swing.JLabel Resettext;
    private javax.swing.JPasswordField confim;
    private javax.swing.JLabel confirmpassword;
    private javax.swing.JButton confirmshowbutton;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField newpass;
    private javax.swing.JLabel newpassword;
    private javax.swing.JLabel passwordreminder;
    private javax.swing.JButton resetbutton;
    private javax.swing.JButton showbutton1;
    private javax.swing.JLabel texttopic;
    // End of variables declaration//GEN-END:variables
}
